#ifndef BMICALCULATOR2_BC2VERSION_IN_H
#define BMICALCULATOR2_BC2VERSION_IN_H

#define VERSION @PROJECT_VERSION_MAJOR@,@PROJECT_VERSION_MINOR@,@PROJECT_VERSION_PATCH@,0
#define VERSION_STR "V@PROJECT_VERSION_MAJOR@.@PROJECT_VERSION_MINOR@.@PROJECT_VERSION_PATCH@"

#endif /* BMICALCULATOR2_BC2VERSION_IN_H */
